
SELECT R.CONTEST_ID, 
    ROUND((COUNT(DISTINCT R.USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USERS))*100, 2) AS PERCENTAGE 
FROM USERS U JOIN REGISTER R ON U.USER_ID = R.USER_ID 
GROUP BY R.CONTEST_ID ORDER BY PERCENTAGE DESC, CONTEST_ID ASC