

SELECT QUERY_NAME, 
    ROUND(SUM(RATING/POSITION)/COUNT(POSITION), 2) AS QUALITY, 
        ROUND((COUNT(CASE WHEN RATING < 3 THEN 1 END)/COUNT(RATING))*100, 2) AS POOR_QUERY_PERCENTAGE 
    FROM QUERIES 
        GROUP BY QUERY_NAME