/* TABLE CITY */


SELECT * FROM CITY
SELECT * FROM CITY WHERE ID=1661
SELECT * FROM CITY WHERE COUNTRYCODE="JPN"
SELECT NAME FROM CITY WHERE COUNTRYCODE="JPN"
SELECT NAME FROM CITY WHERE COUNTRYCODE="USA" AND POPULATION > 120000
SELECT * FROM CITY WHERE COUNTRYCODE="USA" HAVING POPULATION > 100000




/* TABLE STATION */
SELECT CITY, STATE FROM STATION
SELECT COUNT(CITY)-COUNT(DISTINCT(CITY)) FROM STATION
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%'
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I' OR CITY LIKE '%O' OR CITY LIKE '%U'
SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY,1) IN ('A','E','I','O','U') AND RIGHT(UPPER(CITY),1) IN ('A','E','I','O','U')
SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY,1) NOT IN ('A','E','I','O','U')
SELECT DISTINCT CITY FROM STATION WHERE RIGHT(UPPER(CITY),1) NOT IN ('A','E','I','O','U')
SELECT DISTINCT CITY FROM STATION WHERE LEFT(UPPER(CITY),1) NOT IN ('A','E','I','O','U') OR RIGHT(UPPER(CITY),1) NOT IN ('A','E','I','O','U')
SELECT DISTINCT CITY FROM STATION WHERE LEFT(UPPER(CITY),1) NOT IN ('A','E','I','O','U') AND RIGHT(UPPER(CITY),1) NOT IN ('A','E','I','O','U')
SELECT DISTINCT CITY FROM STATION WHERE MOD(ID,2)=0



/* TABLE EMPLOYEE */
SELECT NAME FROM EMPLOYEE ORDER BY NAME ASC
SELECT NAME FROM EMPLOYEE WHERE SALARY > 2000 AND MONTHS < 10 ORDER BY EMPLOYEE_ID ASC



/* TABLE EMPLOYEE */
SELECT NAME FROM STUDENTS WHERE MARKS>75 ORDER BY RIGHT(UPPER(NAME),3) ASC, ID ASC