

/* POPULATION */
SELECT COUNT(NAME) FROM CITY WHERE POPULATION > 100000
SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT = 'California'
SELECT AVG(POPULATION) FROM CITY WHERE DISTRICT = 'California'
SELECT ROUND(AVG(POPULATION)) FROM CITY
SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = 'JPN'
SELECT MAX(POPULATION)-MIN(POPULATION) FROM CITY

/* STATION */
SELECT ROUND(SUM(LAT_N), 2), ROUND(SUM(LONG_W), 2) FROM STATION
SELECT ROUND(MAX(LAT_N),4) FROM STATION WHERE LAT_N < 137.2345;
SELECT ROUND(MIN(LAT_N),4) FROM STATION WHERE LAT_N > 38.77880
SELECT SUM(LAT_N) FROM STATION WHERE LAT_N > 38.7880 AND LAT_N < 137.2345;
SELECT ROUND(LONG_W,4) FROM STATION WHERE LAT_N = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345)
SELECT ROUND(LONG_W, 4) FROM STATION WHERE LAT_N = (SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.77880)
/* MANHATTAN DISTANCE CALCULATION = ABS((x1-x2)+(y1-y2)) */
SELECT ROUND(ABS((MIN(LAT_N)-MAX(LAT_N)) + (MIN(LONG_W)-MAX(LONG_W))),4) FROM STATION
/* EUCLIEDIAN DISTANCE CALCULATION = SQRT((x1-x2)**2+(y1-y2)**2) */
SELECT ROUND(SQRT(POWER((MIN(LAT_N)-MAX(LAT_N)),2) + POWER((MIN(LONG_W)-MAX(LONG_W)),2)),4) FROM STATION

/* MEDIAN */
SELECT
    ROUND(avg(a.LAT_N),4)
FROM (
    SELECT
        ROW_NUMBER() OVER (ORDER BY LAT_N) AS rn,
        COUNT(*) OVER () AS total_count,
    LAT_N
    FROM STATION) AS a
WHERE rn BETWEEN total_count/2 AND (total_count/2)+1


/* EMPLOYEE */
SELECT CEIL(AVG(SALARY) - AVG(CAST(REPLACE(SALARY, '0', '') AS UNSIGNED))) FROM EMPLOYEES

/* EMPLOYEES */
SELECT MAX(SALARY*MONTHS), COUNT(*) FROM EMPLOYEE WHERE SALARY*MONTHS = (SELECT MAX(SALARY*MONTHS) FROM EMPLOYEE)